version: "3.9"

services:
  app:
    build: .
    ports:
      - "80:80"
    environment:
      MONGO_URI: <uri>
      MONGO_DB: <database>
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"
